-- Generated by scripts/import-question-bank.py -- do not edit by hand.
-- Run as the postgres role (SQL Editor); service_role has no insert grant here.

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-001', 'A garment factory receives fabric with significant shade variation between rolls. What is the most appropriate action?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Mix all rolls during spreading', 1),
      ('B', 'Ignore the variation if the fabric is within width specification', 2),
      ('C', 'Identify and segregate different shades before cutting', 3),
      ('D', 'Send all fabric directly to sewing', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-002', 'What is the main purpose of a production line balancing exercise?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To increase fabric weight', 1),
      ('B', 'To distribute work among operations to reduce bottlenecks', 2),
      ('C', 'To eliminate quality inspection', 3),
      ('D', 'To reduce garment measurements', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-003', 'GSM in textiles refers to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Garment Sewing Measurement', 1),
      ('B', 'Grams per Square Metre', 2),
      ('C', 'General Stitch Measurement', 3),
      ('D', 'Garment Standard Method', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-004', 'What does fabric grain generally indicate?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Direction of yarns in woven fabric', 1),
      ('B', 'Fabric colour intensity', 2),
      ('C', 'Fabric thickness only', 3),
      ('D', 'Number of garment panels', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-005', 'What is fabric shrinkage?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Increase in fabric weight', 1),
      ('B', 'Reduction in fabric dimensions after washing or processing', 2),
      ('C', 'Increase in fabric width during sewing', 3),
      ('D', 'Change in fabric colour only', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-006', 'Which fabric property is particularly important when selecting sewing machine settings?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Fabric colour only', 1),
      ('B', 'Fabric thickness, construction and elasticity', 2),
      ('C', 'Brand name', 3),
      ('D', 'Packaging method', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-007', 'Why must buttons, zippers and labels be checked before production?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To increase machine RPM', 1),
      ('B', 'To ensure they match specifications and garment requirements', 2),
      ('C', 'To reduce operator wages', 3),
      ('D', 'To eliminate fabric inspection', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-008', 'The primary purpose of a presser foot is to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Cut the thread', 1),
      ('B', 'Hold the fabric against the feed mechanism while sewing', 2),
      ('C', 'Wind the bobbin', 3),
      ('D', 'Change needle size', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-009', 'What is the function of the needle bar?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Controls fabric width', 1),
      ('B', 'Holds and moves the needle vertically', 2),
      ('C', 'Controls bobbin winding', 3),
      ('D', 'Cuts fabric', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-010', 'Maximum speed of a modern Electronic Sewing Machine is', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '2,500 rpm', 1),
      ('B', '3,500 rpm', 2),
      ('C', '4500 rpm', 3),
      ('D', '6,000 rpm', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-013', 'Cylinder-bed machines are particularly useful for:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Large flat fabric panels only', 1),
      ('B', 'Tubular and curved garment components', 2),
      ('C', 'Fabric inspection', 3),
      ('D', 'Button storage', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-014', 'Which machine is commonly used to finish raw fabric edges and prevent fraying?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Overlock machine', 1),
      ('B', 'Buttonhole machine', 2),
      ('C', 'Button sewing machine', 3),
      ('D', 'Blind stitch machine', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-015', 'Which factor should primarily determine needle selection?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Operator age', 1),
      ('B', 'Fabric type and thread size', 2),
      ('C', 'Garment colour only', 3),
      ('D', 'Machine table size', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-016', 'If repeated skipped stitches occur on a knit fabric, which should be checked first?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Needle type, size and condition', 1),
      ('B', 'Carton dimensions', 2),
      ('C', 'Garment label', 3),
      ('D', 'Fabric colour', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-017', 'How many divisions are between 1’’ of a measuring tape ?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '2', 1),
      ('B', '4', 2),
      ('C', '6', 3),
      ('D', '8', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'D';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-019', 'How to prevent Shrinkage ? Wash the cloth before cutting', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Pressure is too tight or too loose', 1),
      ('B', 'Wash the cloth after cutting', 2),
      ('C', 'Wash the cloth after marking', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-020', 'Which needle is used in a single-needle lockstitch machine ?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'DB X 1', 1),
      ('B', 'DC X 1', 2),
      ('C', 'TQ X 5', 3),
      ('D', 'DP X 17', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-021', 'How fabric will be cut at the time of making a garment ?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Four fold', 1),
      ('B', 'Three fold', 2),
      ('C', 'Bias', 3),
      ('D', 'On grain', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'D';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-022', 'What is the possible cause of Skip Stitch?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Wrong size of the needle', 1),
      ('B', 'Stitching too fast', 2),
      ('C', 'Insufficient oiling', 3),
      ('D', 'A lint in the bobbin case', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-023', 'A paper guide that minimizes the amount of fabric wasted in cutting is called a:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Spreader', 1),
      ('B', 'Roller', 2),
      ('C', 'Marker', 3),
      ('D', 'Digitized table', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-024', 'Blind stitch is a type of .', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Hemming', 1),
      ('B', 'Over lock', 2),
      ('C', 'Edge stitch', 3),
      ('D', 'Chain stitch', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-026', 'If the machine belt is too loose, then –', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Machine will run slowly', 1),
      ('B', 'Machine will run smoothly', 2),
      ('C', 'Machine will not run', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-027', 'The section of a sewing line in which individual parts of a garment is made is known as .', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Assembly', 1),
      ('B', 'Preparatory', 2),
      ('C', 'Both', 3),
      ('D', 'None of the above', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-028', 'Short grove is a part of', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Needle Plate', 1),
      ('B', 'Feed Dog', 2),
      ('C', 'Pressure Foot', 3),
      ('D', 'Needle', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-029', 'What is Thread Tex?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Number of threads', 1),
      ('B', 'Ply of thread', 2),
      ('C', 'Strength of thread', 3),
      ('D', 'Weight of thread', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'D';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-030', 'SPI stands for', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Seam per inch', 1),
      ('B', 'Stitch per inch', 2),
      ('C', 'Strength per inch', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-031', 'Selvedge is a tightly woven edge of fabric that runs parallel to the-----______________   grain.', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Widthwise', 1),
      ('B', 'Crosswise', 2),
      ('C', 'Lengthwise', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-032', '______________ is a semi-circular disc with a hole to allow the needle to pass through it.', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Needle plate', 1),
      ('B', 'Feed Dog', 2),
      ('C', 'Shuttle', 3),
      ('D', 'Needle Bar', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-033', 'What is machine downtime?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Run time of machine', 1),
      ('B', 'Machine Breakdown time', 2),
      ('C', 'Seeking Time', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-034', 'Production of any style is done with reference to ______________ sample.', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Proto', 1),
      ('B', 'Sealer', 2),
      ('C', 'Salesman', 3),
      ('D', 'TOP', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-035', 'SAM stands for ______________', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Single Allowed Minute', 1),
      ('B', 'Standard Minute Value', 2),
      ('C', 'Standard Allowed Value', 3),
      ('D', 'Standard Allowed Minute', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'D';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-036', 'If an operator is making 5 pieces in 6 minutes, then how many pieces can he/she make in 2:30 hours?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '120', 1),
      ('B', '125', 2),
      ('C', '130', 3),
      ('D', 'None of these', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-037', 'Fishbone diagram is used for ______________', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Production Monitoring', 1),
      ('B', 'Finding root cause', 2),
      ('C', 'Matching', 3),
      ('D', 'Line Balancing', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-038', 'What is the likely result of incorrect upper-thread threading?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Improved stitch balance', 1),
      ('B', 'Thread breakage, poor tension or skipped stitches', 2),
      ('C', 'Increased fabric GSM', 3),
      ('D', 'Correct seam automatically', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-039', 'Why must the thread pass through the tension discs correctly?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To control thread tension', 1),
      ('B', 'To increase needle size', 2),
      ('C', 'To control fabric width', 3),
      ('D', 'To change stitch type', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-040', 'A bobbin wound too loosely may cause:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Uneven thread delivery', 1),
      ('B', 'Improved tension', 2),
      ('C', 'Better seam strength', 3),
      ('D', 'No effect whatsoever', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-041', 'When a folder is incorrectly aligned, the most likely result is:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Inconsistent folding and seam appearance', 1),
      ('B', 'Higher fabric GSM', 2),
      ('C', 'Improved quality automatically', 3),
      ('D', 'Lower needle temperature', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-042', 'Correct thread tension is important because it affects:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Stitch formation and seam appearance', 1),
      ('B', 'Fabric colour only', 2),
      ('C', 'Garment packaging only', 3),
      ('D', 'Machine table height', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-043', 'Tension should normally be adjusted:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Randomly during production', 1),
      ('B', 'According to fabric, thread and stitch requirements', 2),
      ('C', 'Only at the end of the shift', 3),
      ('D', 'Without testing', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-044', 'If bobbin winding tension is too high, the bobbin may:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Become wound tightly and affect thread delivery', 1),
      ('B', 'Automatically improve stitch quality', 2),
      ('C', 'Become larger in diameter', 3),
      ('D', 'Change fabric properties', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-045', 'What is a bottleneck?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'An operation that limits the overall production flow', 1),
      ('B', 'A high-performing operation', 2),
      ('C', 'A quality inspection document', 3),
      ('D', 'A type of needle', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-046', 'Ergonomics primarily aims to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Fit the workplace and work method to the worker', 1),
      ('B', 'Increase machine noise', 2),
      ('C', 'Increase operator fatigue', 3),
      ('D', 'Reduce quality inspections', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-047', 'Which seating condition is generally most appropriate for sewing operators?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Adjustable and supportive seating with suitable working height', 1),
      ('B', 'Very high stool without back support', 2),
      ('C', 'Standing on one foot', 3),
      ('D', 'Fixed seating regardless of operator height', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-048', 'When reading a measuring tape, the measurement should be taken:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'From the approximate middle of the tape', 1),
      ('B', 'From the correct zero/reference point', 2),
      ('C', 'From any convenient mark', 3),
      ('D', 'From the end of the garment label', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-049', 'Full of POM.', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Point of Measure', 1),
      ('B', 'Point of Measurement', 2),
      ('C', 'Point of Marking', 3),
      ('D', 'Point of Material', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-050', 'In garment manufacturing, quality primarily means:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Meeting specified requirements consistently', 1),
      ('B', 'Producing the maximum number of pieces regardless of defects', 2),
      ('C', 'Using the cheapest materials', 3),
      ('D', 'Completing production without inspection', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-051', 'Quality should primarily be controlled:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Only at final inspection', 1),
      ('B', 'Throughout the production process', 2),
      ('C', 'Only after packing', 3),
      ('D', 'Only by supervisors', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-052', 'Seam puckering can be caused by:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Incorrect thread tension, feeding or machine settings', 1),
      ('B', 'Correct tension only', 2),
      ('C', 'Proper fabric handling', 3),
      ('D', 'Correct needle selection', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-053', 'What is a skipped stitch?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'A stitch formation failure where the required stitch is missing', 1),
      ('B', 'A longer seam allowance', 2),
      ('C', 'A type of fabric', 3),
      ('D', 'A button defect', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-054', 'If stitches repeatedly break at the same location, which should be investigated?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Thread path, needle, tension and machine condition', 1),
      ('B', 'Packaging carton colour', 2),
      ('C', 'Garment label size only', 3),
      ('D', 'Cutting room lighting only', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-055', 'Uneven seam allowance is most directly related to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Poor fabric handling or guide control', 1),
      ('B', 'Fabric GSM only', 2),
      ('C', 'Carton size', 3),
      ('D', 'Button colour', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-056', 'Shade variation can become a serious garment quality issue when:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Panels from visibly different shades are assembled together', 1),
      ('B', 'All panels are from the same shade lot', 2),
      ('C', 'The garment is correctly measured', 3),
      ('D', 'The sewing machine is clean', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-057', 'A fabric slub is generally associated with:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'An irregularity in yarn appearance', 1),
      ('B', 'Correct stitch formation', 2),
      ('C', 'Button placement', 3),
      ('D', 'Seam allowance', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-058', 'Why is early defect detection important?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'It reduces rework and prevents defects from moving downstream', 1),
      ('B', 'It increases rework', 2),
      ('C', 'It increases fabric consumption', 3),
      ('D', 'It delays production unnecessarily', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-059', 'Why should the sewing machine work area be kept clean?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To improve safety, productivity and machine performance', 1),
      ('B', 'Only to make the workplace attractive', 2),
      ('C', 'To increase garment weight', 3),
      ('D', 'To reduce garment size', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-060', 'Broken needle pieces should be:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Thrown into general waste', 1),
      ('B', 'Properly collected and accounted for according to workplace procedure', 2),
      ('C', 'Left beside the machine', 3),
      ('D', 'Placed inside fabric bundles', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-061', 'What is preventive maintenance?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Maintenance performed only after machine breakdown', 1),
      ('B', 'Planned maintenance performed to prevent failures', 2),
      ('C', 'Repair performed only during emergencies', 3),
      ('D', 'Replacement of garments', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-062', 'Why is regular machine cleaning important?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Needle condition → thread path → tension → needle/thread compatibility', 1),
      ('B', 'Fabric colour → label → packaging', 2),
      ('C', 'Operator attendance → production target', 3),
      ('D', 'Carton size → garment measurement', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-063', 'A needle repeatedly breaks when the operator approaches a thick seam. Which corrective action is MOST appropriate?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Increase machine speed', 1),
      ('B', 'Check needle size, needle condition, presser-foot pressure and material thickness', 2),
      ('C', 'Reduce bobbin thread', 3),
      ('D', 'Increase upper-thread tension immediately', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-064', 'For a typical woven men''s shirt, which sequence is most logically arranged to maintain component accuracy and minimize rework?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Attach buttons → make collar → join shoulders → attach sleeves', 1),
      ('B', 'Prepare components → construct major assemblies → attach sleeves/side seams → finishing operations', 2),
      ('C', 'Pack → inspect → sew collar', 3),
      ('D', 'Hem → pack → attach collar', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-065', 'An operator consistently produces a 10 mm seam when the specification requires 12 mm. Which is the BEST corrective action?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Increase the operator''s speed', 1),
      ('B', 'Correct the guide/folder position and verify the method using a sample', 2),
      ('C', 'Ask finishing to compensate', 3),
      ('D', 'Reduce garment size specification', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-066', 'A hole is found in the garment panel before sewing. Which classification is most appropriate?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Sewing defect', 1),
      ('B', 'Fabric defect', 2),
      ('C', 'Finishing defect', 3),
      ('D', 'Packing defect', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-067', 'A shirt chest specification is 102 cm ± 1 cm. Which measurement is OUTSIDE the acceptable tolerance?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '101.2 cm', 1),
      ('B', '102.5 cm', 2),
      ('C', '102.7 cm', 3),
      ('D', '102.8 cm', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-068', 'An operation has the following elemental times: Pick up panel = 0.08 min Align panel = 0.12 min Sewing = 0.45 min Cut thread/finish = 0.10 min Ignoring allowances, what is the basic operation time?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '0.55 min', 1),
      ('B', '0.65 min', 2),
      ('C', '0.75 min', 3),
      ('D', '0.85 min', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-069', 'What is meant by efficiency in the garment industry?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'The percentage of workers present on the production floor', 1),
      ('B', 'The ability to achieve the required output using the available time and resources effectively', 2),
      ('C', 'The total number of machines available in a production line', 3),
      ('D', 'The time taken to complete a garment inspection', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-070', 'An operation has an SMV of 1.2 minutes. An operator works for 60 minutes at 75% efficiency. What is the expected output?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '30 pieces', 1),
      ('B', '37.5 pieces', 2),
      ('C', '50 pieces', 3),
      ('D', '60 pieces', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-071', 'A line''s actual output is significantly below target, but individual operators appear busy. Which is the best first IE approach?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Immediately increase all machine speeds', 1),
      ('B', 'Study cycle times, bottlenecks, WIP and line balance', 2),
      ('C', 'Remove quality inspection', 3),
      ('D', 'Increase the target without analysis', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-072', 'In a Single Needle Lockstitch machine, the hook mechanism is primarily responsible for:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Moving the fabric forward', 1),
      ('B', 'Interlocking the upper thread loop with the bobbin thread', 2),
      ('C', 'Controlling presser-foot pressure', 3),
      ('D', 'Cutting the fabric', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-073', 'What is the primary function of the take-up lever in an SNLS machine?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Controls fabric feeding', 1),
      ('B', 'Supplies and pulls back the upper thread during stitch formation', 2),
      ('C', 'Holds the bobbin', 3),
      ('D', 'Controls needle size', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-074', 'What is the primary function of the throat plate?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Supports the fabric around the needle penetration area', 1),
      ('B', 'Controls thread colour', 2),
      ('C', 'Winds the bobbin', 3),
      ('D', 'Controls motor speed', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-075', 'Why should a trainer consider both needle size and thread size when setting up an operation?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Their compatibility affects stitch formation and fabric damage', 1),
      ('B', 'They determine garment colour', 2),
      ('C', 'They determine carton size', 3),
      ('D', 'They have no relationship', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-076', 'The purpose of a walking-foot mechanism is primarily to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Improve feeding of difficult or multiple layers by assisting material movement', 1),
      ('B', 'Wind the bobbin', 2),
      ('C', 'Make buttonholes', 3),
      ('D', 'Cut threads', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-077', 'If an overlock seam on knit fabric is stretching excessively, which setting should be investigated?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Differential feed and presser-foot pressure', 1),
      ('B', 'Buttonhole density', 2),
      ('C', 'Bobbin winding only', 3),
      ('D', 'Garment label position', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-078', 'A machine suddenly starts producing skipped stitches after the needle bar has been adjusted. What should the trainer suspect?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Incorrect needle-bar height or hook timing', 1),
      ('B', 'Fabric colour', 2),
      ('C', 'Garment packing', 3),
      ('D', 'Measuring tape', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-079', 'During shirt side-seam sewing, the front and back panels are not matching at the hem. Which is the most likely operational cause?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Uneven feeding or inaccurate panel alignment', 1),
      ('B', 'Correct sewing method', 2),
      ('C', 'Buttonhole size', 3),
      ('D', 'Label colour', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-080', 'What is the primary purpose of a sewing machine guide?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To control thread tension', 1),
      ('B', 'To maintain consistent fabric position and seam allowance', 2),
      ('C', 'To increase machine RPM', 3),
      ('D', 'To control bobbin winding', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-081', 'An operator is using a hem folder. The finished hem width varies by 2–3 mm along the garment. Machine speed and stitch length are correct. What should the trainer check FIRST?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Folder alignment and fabric feeding into the folder', 1),
      ('B', 'Bobbin colour', 2),
      ('C', 'Needle-bar height', 3),
      ('D', 'Garment packing', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-082', 'What is the most likely consequence of applying excessive oil near the sewing area?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Improved stitch quality', 1),
      ('B', 'Oil stains on garments and possible contamination', 2),
      ('C', 'Increased needle strength', 3),
      ('D', 'Reduced machine vibration', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-083', 'An operator breaks a sewing needle during production. What should be the FIRST action?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Continue sewing with a new needle', 1),
      ('B', 'Stop the machine safely and control the work area', 2),
      ('C', 'Throw the broken needle into the general waste bin', 3),
      ('D', 'Give the broken needle to another operator', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-084', 'A needle breaks while sewing a garment containing several layers. The operator immediately replaces the needle but does not inspect the garment. What is the main policy concern?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'The garment may contain an undetected needle fragment', 1),
      ('B', 'The garment may become heavier', 2),
      ('C', 'The thread may change colour', 3),
      ('D', 'The SMV will increase automatically', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-085', 'What is the main purpose of a work study in garment production?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To increase fabric consumption', 1),
      ('B', 'To determine the most efficient method and time required for an operation', 2),
      ('C', 'To reduce the number of operators without analysis', 3),
      ('D', 'To increase machine noise', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-086', 'If an operator’s actual cycle time is higher than the standard time, what should be checked first?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Garment colour', 1),
      ('B', 'Method, machine condition, material handling and operator movement', 2),
      ('C', 'Packaging design', 3),
      ('D', 'Fabric shade only', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-087', 'What is WIP in garment manufacturing?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Work in Process', 1),
      ('B', 'Work Inspection Procedure', 2),
      ('C', 'Worker Improvement Plan', 3),
      ('D', 'Width Inspection Point', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-088', 'Excessive WIP between two operations usually indicates:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Perfect line balancing', 1),
      ('B', 'A possible bottleneck or imbalance between operations', 2),
      ('C', 'Reduced fabric consumption', 3),
      ('D', 'Improved quality automatically', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-089', 'What is the main purpose of a bundle ticket in garment production?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To increase sewing speed', 1),
      ('B', 'To identify and track garment components through production', 2),
      ('C', 'To measure fabric GSM', 3),
      ('D', 'To adjust needle tension', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-090', 'A garment has correct measurements but poor seam appearance. Which area should be investigated?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Stitch formation, thread tension, needle and machine settings', 1),
      ('B', 'Carton size', 2),
      ('C', 'Fabric purchase price', 3),
      ('D', 'Operator attendance only', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-091', 'What is rework in garment production?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Producing a new style', 1),
      ('B', 'Correcting a garment or component to meet the required specification', 2),
      ('C', 'Increasing machine speed', 3),
      ('D', 'Replacing all fabric', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-092', 'If a quality defect is repeatedly occurring at the same operation, the best approach is to:', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Ignore it until final inspection', 1),
      ('B', 'Identify and eliminate the root cause of the defect', 2),
      ('C', 'Increase the production target', 3),
      ('D', 'Transfer the defect to the next operation', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-093', 'What is the purpose of a standard operating procedure (SOP)?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To provide a consistent and defined method for performing an operation', 1),
      ('B', 'To increase garment price', 2),
      ('C', 'To eliminate operator training', 3),
      ('D', 'To reduce the number of machines', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-094', 'A line produces 480 pieces in 8 hours. What is the average production per hour?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '50 pieces', 1),
      ('B', '60 pieces', 2),
      ('C', '70 pieces', 3),
      ('D', '80 pieces', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'B';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-095', 'What is the primary purpose of a production target?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To define the required output for a given period', 1),
      ('B', 'To increase fabric GSM', 2),
      ('C', 'To eliminate quality checks', 3),
      ('D', 'To reduce the number of operators', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-096', 'What does SMV help determine in garment production?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'The standard time required to perform an operation', 1),
      ('B', 'Fabric colour', 2),
      ('C', 'Garment selling price only', 3),
      ('D', 'Number of buttons', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-097', 'If an operation has a cycle time greater than the line takt/cycle requirement, what is the likely effect?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'It may become a bottleneck', 1),
      ('B', 'It will automatically improve quality', 2),
      ('C', 'It will reduce fabric width', 3),
      ('D', 'It will eliminate WIP', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-098', 'What is the purpose of first-piece inspection?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'To verify that the operation and product meet requirements before continuing production', 1),
      ('B', 'To increase machine speed', 2),
      ('C', 'To replace final inspection completely', 3),
      ('D', 'To increase fabric consumption', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-099', 'Which action is most appropriate when a recurring defect is identified?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', 'Contain the defect, identify the root cause and implement corrective action', 1),
      ('B', 'Ignore it until shipment', 2),
      ('C', 'Increase production speed immediately', 3),
      ('D', 'Move the defect to the next operation', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'A';

with q as (
  insert into public.questions (
    assessment_version_id, external_code, question_text, marks,
    category, difficulty, explanation, is_active
  )
  values (
    '40000000-0000-4000-8000-000000000001', 'GMQ-100', 'A line has a target of 400 pieces in 8 hours and produces 360 pieces. What percentage of the target was achieved?', 1,
    null, null, null, true
  )
  returning id
), o as (
  insert into public.question_options (question_id, option_code, option_text, display_order)
  select q.id, v.code, v.text, v.ord
  from q
  cross join (
    values
      ('A', '80%', 1),
      ('B', '85%', 2),
      ('C', '90%', 3),
      ('D', '95%', 4)
  ) as v(code, text, ord)
  returning id, question_id, option_code
)
insert into private.question_answer_keys (question_id, correct_option_id)
select o.question_id, o.id from o where o.option_code = 'C';
